chat_llm_args:
  type: nvidia
  model_name: google/gemma-2-9b-it
  temperature: 0.3
  max_tokens: 4096
  
   
db_args:
  type:faiss
  vector_store_path: "./data/vector_db/knowledge_base/"
  chunk_size: "./data/vector_db/knowledge_base/"
  chunk_overlap: true
  output_path:
  docs_path: "./data/vector_db/preprocessed/"


  

embedder_args:
  type: huggingaface
  model_name: sentence-transformers/all-mpnet-base-v2
  model_kwargs:
    device: cpu
  encode_kwargs:
    normalize_embeddings: true
  model_path: "./src/embedder/model_checkpoints/"
  


